import 'bootstrap/dist/css/bootstrap.min.css'
import '../styles/style.css'
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

import type { AppProps } from 'next/app'
import { AppNavBar } from '@/components/AppNavBar'
import { MyFooter } from '@/components/MyFooter'
import { createContext, useState } from 'react'
import { Container } from 'react-bootstrap'
import Head from 'next/head'

export const LanguageContext = createContext('IT')
export function chooseWordForActualLanguage(
  language: string,
  italianWord?: string,
  englishWord?: string,
) {
  if (englishWord && italianWord)
    return language === 'IT' ? italianWord : englishWord
  else return 'undefined'
}

export default function App({ Component, pageProps }: AppProps) {
  let [language, setLanguage] = useState('EN')

  let setItalian = function () {
    setLanguage('IT')
  }

  let setEnglish = function () {
    setLanguage('EN')
  }

  return (
    <>
      <LanguageContext.Provider value={language}>
        <AppNavBar />
        <Head>
          <title>Edoardo Colella</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Container className="text-center">
            <Component {...pageProps} />
          </Container>
        </main>
        <MyFooter setItalian={setItalian} setEnglish={setEnglish} />
      </LanguageContext.Provider>
    </>
  )
}
